version: "3.9"
services:
     
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      #- USER=username #optional
      #- PASS=password #optional
      #- WHITELIST=iplist #optional
      #- HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./transmission:/config      
      - /srv/dev-disk-by-uuid-d7ac13bc-1cd8-4f58-bad4-546dbfc62ed2/DiskX:/downloads
      #- /srv/dev-disk-by-uuid-773f89aa-49b6-42b1-9f72-5813d390f08e/DiskX
      - ./transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped   