homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
  user: admin
  password: '542402'
serial:
  port: /dev/ttyACM0
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
device_options:
  legacy: false
frontend:
  port: 8080
  auth_token: '542402'
  host: 0.0.0.0
devices:
  '0x00158d0002b17aca':
    friendly_name: Vhod
  '0x00158d0000dac98c':
    friendly_name: Vozduh1
